{% if not WITH_SOLVERS is defined %}
  {% set WITH_SOLVERS = 1 %}
{% endif %}
{% set WITH_SOLVERS = WITH_SOLVERS|int %}

{% if not WITH_GUI is defined %}
  {% set WITH_GUI = 1 %}
{% endif %}
{% set WITH_GUI = WITH_GUI|int %}

package:
  {% if WITH_GUI %}
    {% if WITH_SOLVERS %}
      name: ilastik-dependencies
    {% else %}
      name: ilastik-dependencies-no-solvers
    {% endif %}
  {% else %}
    {% if WITH_SOLVERS %}
      name: ilastik-dependencies-no-gui
    {% else %}
      name: ilastik-dependencies-no-solvers-no-gui
    {% endif %}
  {% endif %}
      version: 1.3

build:
  number: 5
  track_features:
    # on osx we need to make sure that we install the numpy versions with openblas instead of mkl to prevent clashes with cplex
    - blas_openblas #[osx] 
#
# In general, we don't specify exact version requirements in each sub-package.
# But this file tracks the versions of all packages used in the release.
requirements:
  run:
    # -----------------------------------------------------------------
    # General dependencies
    # -----------------------------------------------------------------
    - python                    3.6*
    - numpy                     1.12*

    - decorator                 
    - fftw                      
    - future                   
    - greenlet                  
    - h5py                      >=2.7.0     
    - hdf5                      >=1.8.17
    - jsonschema                
    - networkx                  1.11          # TODO API change in 2.0
    - nose                      
    - psutil                    
    - python-dateutil                
    - pytz                      
    - qimage2ndarray            
    - qt                        5.6*
    - readline                                 # [not win]
    - requests                  
    - scikit-image              
    - scikit-learn              
    - setuptools                
    - matplotlib
    - mkl                       2017.0.3*      # [win]

{% if WITH_GUI %}
    - pyqt                      5.6*
    - pyqtgraph
    - pyopengl
{% endif %}

    # -----------------------------------------------------------------
    # packages built by us
    # -----------------------------------------------------------------
    - pytiff                    
    - tifffile                  0.4.post2
    - yapsy                     
    - lemon    

    # -----------------------------------------------------------------
    # ilastik main packages developed by us
    # -----------------------------------------------------------------
    - ilastik-feature-selection 
    - iiboost                                  # [not win]
    - ilastiktools              
    - ilastikrag                
    - wsdt                 
    - numpy-allocation-tracking
    - vigra                     >=1.11.1                 
    - ilastik-meta
    - ilastik-launch                           # [not win]

    # -----------------------------------------------------------------
    # Tracking
    # -----------------------------------------------------------------
    - dpct                      
    - hytra                     
    - mamutexport               

{% if WITH_SOLVERS %}
    - multi-hypotheses-tracking-with-gurobi
    - multi-hypotheses-tracking-with-cplex
{% endif %}

    
    # -----------------------------------------------------------------
    # Multicut
    # -----------------------------------------------------------------
    - nifty                     
    
{% if WITH_SOLVERS %}
    - nifty-with-cplex
    - nifty-with-gurobi
{% endif %}

test:
  # Just give SOME test to ensure that the package can be installed at all.
  # (If there are no tests, the test environment isn't even created.)
  imports:
    - vigra

about:
  home: https://github.com/ilastik-build-conda
  license: BSD (3-clause)
  summary: 'Package for all dependencies needed to run ilastik'
