package:
  name: vigra

  # Transform tag:
  # Version-1-11-0 --> 1.11.0
  {% set tagged_version = GIT_DESCRIBE_TAG|replace("Version-","")|replace("-", ".") %}

  # If we're using a non-tagged revision, append '.postN' to the version
  {% if GIT_DESCRIBE_NUMBER|int != 0 %}
    {% set tagged_version = tagged_version + '.post' + GIT_DESCRIBE_NUMBER %}
  {% endif %}

  version: {{tagged_version}}

source:
  git_url: https://github.com/ukoethe/vigra
  git_tag: HEAD

build:
  features:
    - vc14 # [win]
  number: 10
  msvc_compiler: 14.0 # [win]
  script_env:
    - VIGRA_SKIP_TESTS
    # Control building with CXX11 abi
    - DO_NOT_BUILD_WITH_CXX11_ABI  # [linux]

requirements:
  build:
    - python 2.7*|3.5*|3.6*
    - python   {{ python }}
    - numpy    {{ numpy }}
    - jpeg     {{ jpeg }}
    - libtiff  4.0.9
    - libpng   {{ libpng }}
    - fftw     3.3*
    - hdf5     {{ hdf5 }}
    - h5py     {{ h5py }}
    - boost    {{ boost }}
    - lemon    {{ lemon }}
    - zlib     1.2*
    - nose

  run:
    - python
    - numpy
    - jpeg
    - libtiff  4.0.9   # libtiff version must exactly match from the build (on osx, at least)
    - libpng
    - fftw     3.3*
    - hdf5
    - h5py
    - boost
    - lemon
    # in order to suppor older linux distros after gcc5 switch:
    - libstdcxx-ng >={{ libstdcxxng }} # [linux]
    - zlib     1.2*
    - nose

test:
  imports:
    - vigra

about:
  home: http://ukoethe.github.io/vigra
  license: MIT
  summary: Generic Programming for Computer Vision

