
package:
  name: lemon
  version: "1.3.1"

source:
  fn: lemon-1.3.1.tar.gz
  url: http://lemon.cs.elte.hu/pub/sources/lemon-1.3.1.tar.gz
  md5: e89f887559113b68657eca67cf3329b5

  # patches:
  #   - lemon.patch
  #   - lemon-test.patch

build:
  number: 1000
requirements:
  build:
    - cmake
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}

about:
  home: http://lemon.cs.elte.hu/trac/lemon
  license: Boost
  summary: Library for Efficient Modeling and Optimization in Networks
